// apps/reactapp/src/app/app.tsx
import React, { useEffect } from 'react';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';

export function App() {
  const childData = {
    text: 'React',
  };

  // Attach event listener to Custom Event
  useEffect(() => {
    window.addEventListener('btn-clicked', eventHandler);
  }, []);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const eventHandler = (event: any) => {
    window.alert(event?.detail.message);
  };

  return (
    <>
      <h1 className="text-lg text-center mt-32 mb-10">Here is React App</h1>
      <merlino-mike-good
        framework={JSON.stringify(childData)}
      ></merlino-mike-good>
    </>
  );
}

export default App;

// apps/angularapp/src/app/app.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'merlino-mike-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})

export class AppComponent {

  // Object that will be passed to Web Component
  childData = {
    text: 'Angular'
  }

  // Json parser
  JSON = JSON;

  // Custom event listener
  @HostListener('window:btn-clicked', ['$event'])
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  onMessage(event: any) {
    window.alert(event.detail?.message);
  }
}


<h1 class="text-lg text-center mt-32 mb-10">Here is Angular App</h1>
<merlino-mike-good [attr.framework]="JSON.stringify(childData)"></merlino-mike-good>
<router-outlet></router-outlet>
